# Generated by Django 3.0.8 on 2020-08-12 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0002_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='hospis',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
