# Generated by Django 3.0.8 on 2020-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0005_details_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='beds',
            field=models.CharField(default=100, max_length=64),
            preserve_default=False,
        ),
    ]
