# Generated by Django 3.0.8 on 2020-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0006_details_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='upd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc', models.CharField(max_length=64)),
                ('avl', models.CharField(max_length=64)),
                ('hnm', models.CharField(max_length=64)),
            ],
        ),
    ]
