# Generated by Django 3.0.8 on 2020-08-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0008_details_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='appt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patname', models.CharField(max_length=64)),
                ('agge', models.CharField(max_length=64)),
                ('probl', models.CharField(max_length=6400)),
                ('datt', models.CharField(max_length=64)),
            ],
        ),
    ]
