# Generated by Django 3.0.8 on 2020-08-12 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0009_appt'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='hnme',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
