# Generated by Django 3.0.8 on 2020-08-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0010_appt_hnme'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvedapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnma', models.CharField(max_length=64)),
                ('pate', models.CharField(max_length=64)),
                ('dat', models.CharField(max_length=64)),
            ],
        ),
    ]
