# Generated by Django 3.0.8 on 2020-08-13 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0011_approvedapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedapp',
            name='urr1',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appt',
            name='urr',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
