# Generated by Django 3.0.8 on 2020-08-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0012_auto_20200813_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos', models.CharField(max_length=64)),
                ('urr', models.CharField(max_length=64)),
                ('raa', models.IntegerField()),
            ],
        ),
    ]
