# Generated by Django 3.0.8 on 2020-08-14 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0013_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
