# Generated by Django 3.0.8 on 2020-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0014_details_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='avg',
            field=models.FloatField(),
        ),
    ]
