# Generated by Django 3.0.8 on 2020-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0015_auto_20200814_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='avg',
            field=models.FloatField(default=0),
        ),
    ]
