# Generated by Django 3.0.8 on 2020-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0016_auto_20200814_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
