# Generated by Django 3.0.8 on 2020-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospiHomes', '0019_auto_20200815_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='pic',
            field=models.ImageField(null=True, upload_to='D:\\EDX\\HospiHome\\HospiHomes\\static\\hospi'),
        ),
    ]
